export {
	type BlockReference,
	type CommentReference,
	type DocView,
	enrichImageHashes,
	findBlockById,
	flattenImageRuns,
	flattenParagraphs,
	type HyperlinkReference,
	type ImageReference,
	openDocView,
	paragraphText,
	paragraphTextAccepted,
	paragraphTextBaseline,
	saveDocView,
	type TrackedChangeReference,
} from "./ast";
export type {
	Block,
	BreakRun,
	ChartRun,
	Comment,
	CommentAnchor,
	Doc,
	DocProperties,
	EquationRun,
	Footnote,
	FootnoteRefRun,
	Hyperlink,
	ImageRun,
	Paragraph,
	Run,
	SectionBreak,
	SectionType,
	Table,
	TableCell,
	TableRow,
	TableWidth,
	TabRun,
	TextRun,
	TrackedChange,
	TrackedChangeKind,
} from "./ast/types";
export {
	type BlockRangeReference,
	type BlockTarget,
	type Locator,
	LocatorParseError,
	LocatorResolveError,
	locatorToBlockTarget,
	parseCellAt,
	parseCellRangeAt,
	parseColumnAt,
	parseLocator,
	parseRowAt,
	parseTableAt,
	resolveBlock,
	resolveBlockRange,
} from "./locators";
export { PkgError } from "./package";
export { ensureContentTypeDefault, nextRelationshipId } from "./package/parts";
export { XmlNode } from "./parser";
export {
	addHyperlinkRelationship,
	HYPERLINK_RELATIONSHIP_TYPE,
	hasRelationshipWithTarget,
	isRelationshipReferenced,
	removeRelationship,
	setRelationshipTarget,
} from "./relationships";
export {
	applyColumns,
	applySectionType,
	isSectionType,
	isTrailingSectPr,
	readSectionProperties,
	removeInlineSectPr,
	type SectionProperties,
	SentinelSectionParagraph,
	wrapSectPrChange,
} from "./sections";
export {
	convertTextToDelText,
	createRevisionAllocator,
	isTrackChangesEnabled,
	mintRevisionMeta,
	type RevisionAllocator,
	resolveAuthor,
	resolveDate,
	type TrackedMeta,
} from "./track-changes";
export { Del, Ins, markParagraphMarkAs } from "./track-changes/emit";
